### ISSUE TITLE
"Download PDF" links raise a 404 "not found" error

### ISSUE THREAD

**Issue by tompollard** [mlresearch/v248#1]
If I go to: https://proceedings.mlr.press/v248/ and click "Download PDF", I am sent to somewhere like: https://raw.githubusercontent.com/mlresearch/v248/main/assets/han24a/han24a.pdf (which raises a 404).

As far as I can see, there are a couple of issues:

1. **Papers are inside an "assets" folder**. Other volumes include a folder for each paper at the project root (e.g. see [v243](https://github.com/mlresearch/v243/) and [v247](https://github.com/mlresearch/v247)). v248 has the content inside an [assets folder](https://github.com/mlresearch/v248/tree/gh-pages/assets).

2. **The URLs in the `_posts/` metadata files are incorrect** (e.g. see: [_posts/2024-07-24-ahsan24a.md](https://github.com/mlresearch/v248/blob/gh-pages/_posts/2024-07-24-ahsan24a.md)). The URLs look like this: 
 
    `https://raw.githubusercontent.com/mlresearch/v248/main/assets/ahsan24a/ahsan24a.pdf` 

    but they should look like this: 

    `https://proceedings.mlr.press/v248/ahsan24a/ahsan24a.pdf` 

    (unless the assets folder above is an intentional change, in which case they should look like this: `https://proceedings.mlr.press/v248/assets/ahsan24a/ahsan24a.pdf`).

@lawrennd please could you help? I'm happy to open a pull request if you can give me guidance on how the files should be reorganised.

**Comment by lawrennd** [comment]
Apologies Tom, it was missing a "main" branch. 

Should be working now.

**Comment by tompollard** [comment]
Thanks Neil!
